name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Update Gradle Wrapper Script Permissions
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build --info
